/* ===================================================================
   FORECAST DATA  — loaded dynamically from Supabase's snapshots table
   Generated by the ML pipeline (XGBoost model), ingested via
   scripts/pkl_to_json.py / .github/workflows/update-forecast-pkl.yml
   Unit: USD per 40ft container (FEU)
   =================================================================== */
let FORECAST_DATA = [];

/* The immediately previous forecast run, kept so the Forecast Result page can
   show how the latest run revised the fee for the same ISD. Empty when only
   one run has ever been ingested. FORECAST_META/PREV_FORECAST_META carry
   each run's generated_at so the UI can date the revision. */
let PREV_FORECAST_DATA  = [];
let FORECAST_META       = { generatedAt: null };
let PREV_FORECAST_META  = { generatedAt: null };

/* Every distinct forecast run, loaded lazily by the Forecast Revisions tab.
   Newest first; each entry is { id, generatedAt, forecast }. */
let SNAPSHOT_RUNS = [];
let SNAPSHOT_RUNS_LOADED = false;

/* Supabase project — see supabase/README.md for setup. */
const SUPABASE_URL = 'https://uioqmeulbvsnqfvtdmzt.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_LzOfDzr4YZ22RUkclX3zVQ_fa37cW-P';

/* Route config — this deployment only supports the NE→USEC lane */
const ROUTES = {
  'ne-usec': { label:'North Europe → US East Coast', origin:'Rotterdam (North Europe)', dest:'New York (US East Coast)', scale:1.00 },
};

const FIXED_ROUTE = 'ne-usec';

/* ===================================================================
   QUOTE HISTORY  — backed by Supabase's quote_requests table (see
   supabase/schema.sql), so quote records are shared across
   devices/sessions instead of trapped in one browser's localStorage.
   =================================================================== */
let HISTORY_DATA = [];

/* Maps a quote_requests row (snake_case, server-generated id) onto the
   camelCase shape the rest of this file already renders. */
function normalizeQuoteRow(r) {
  const created = new Date(r.created_at);
  return {
    id: r.id,
    ts: created.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) + '\n' +
        created.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
    company: r.company, pic: r.pic, route: r.route,
    isdDate: r.isd_date, containers: r.containers, isdFee: r.isd_fee,
    lowDate: r.low_date, lowFee: r.low_fee, clientDate: r.client_date,
    status: r.status, decision: r.decision_date,
    /* Null until the quotation is issued — see issueQuotationFor(). */
    quoteRef: r.quote_ref, issuedAt: r.issued_at, validUntil: r.valid_until,
    quotedFee: r.quoted_fee == null ? null : Number(r.quoted_fee),
    quotedPrice: r.quoted_price == null ? null : Number(r.quoted_price),
    forecastGeneratedAt: r.forecast_generated_at,
  };
}

async function initHistory() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/quote_requests?select=*&order=created_at.desc`, {
    headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}` },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const rows = await res.json();
  HISTORY_DATA = rows.map(normalizeQuoteRow);
}

/* Creates the Pending record in quote_requests and returns the
   normalized row, including its server-assigned id. */
async function insertHistoryRecord(entry) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/quote_requests`, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json', Prefer: 'return=representation',
    },
    body: JSON.stringify({
      company: entry.company, pic: entry.pic, route: entry.route,
      isd_date: entry.isdDate, containers: entry.containers, isd_fee: entry.isdFee,
      low_date: entry.lowDate, low_fee: entry.lowFee, client_date: entry.clientDate,
      status: 'Pending',
    }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const [row] = await res.json();
  const normalized = normalizeQuoteRow(row);
  HISTORY_DATA.unshift(normalized);
  return normalized;
}

/* Patches an existing record (client_date/status/decision_date) in
   quote_requests and updates the in-memory cache. */
async function updateHistoryRecord(id, patch) {
  const body = {};
  if ('clientDate' in patch) body.client_date = patch.clientDate;
  if ('status'     in patch) body.status = patch.status;
  if ('decision'   in patch) body.decision_date = patch.decision;
  /* Editable request details — written by the Edit Record modal on the
     Forecast History page (see saveEditRecord()). The database refuses these
     on an issued quotation, which is why the modal only opens on rows that
     are still Pending and un-issued. */
  if ('company'    in patch) body.company = patch.company;
  if ('pic'        in patch) body.pic = patch.pic;
  if ('containers' in patch) body.containers = patch.containers;
  if ('isdDate'    in patch) body.isd_date = patch.isdDate;
  if ('isdFee'     in patch) body.isd_fee  = patch.isdFee;
  if ('lowDate'    in patch) body.low_date = patch.lowDate;
  if ('lowFee'     in patch) body.low_fee  = patch.lowFee;
  /* Issue fields — written once, by issueQuotationFor(). The database rejects
     any later attempt to change them (see schema.sql's lock trigger). */
  if ('quoteRef'    in patch) body.quote_ref    = patch.quoteRef;
  if ('issuedAt'    in patch) body.issued_at    = patch.issuedAt;
  if ('validUntil'  in patch) body.valid_until  = patch.validUntil;
  if ('quotedFee'   in patch) body.quoted_fee   = patch.quotedFee;
  if ('quotedPrice' in patch) body.quoted_price = patch.quotedPrice;
  if ('forecastGeneratedAt' in patch) body.forecast_generated_at = patch.forecastGeneratedAt;
  body.updated_at = new Date().toISOString();

  const res = await fetch(`${SUPABASE_URL}/rest/v1/quote_requests?id=eq.${id}`, {
    method: 'PATCH',
    headers: {
      apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json', Prefer: 'return=representation',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const [row] = await res.json();
  const normalized = normalizeQuoteRow(row);
  const idx = HISTORY_DATA.findIndex(h => h.id === id);
  if (idx !== -1) HISTORY_DATA[idx] = normalized;
  return normalized;
}

/* Deletes a record outright — the D of the CRUD set, and the only operation
   here that destroys data rather than adding to it.

   The database is the authority on what may be deleted (schema.sql's
   "Delete pending requests" policy plus its delete guard); this function
   only carries the request. That split matters: an RLS policy that matches
   no row deletes nothing and still returns 200, so an empty response body
   means "the rules refused this row", not "done". Callers need to tell those
   apart, hence return=representation and the explicit check below. */
async function deleteHistoryRecord(id) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/quote_requests?id=eq.${id}`, {
    method: 'DELETE',
    headers: {
      apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      Prefer: 'return=representation',
    },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const rows = await res.json();
  if (!rows.length) {
    const err = new Error('Deletion was refused by the database rules.');
    err.blocked = true;
    throw err;
  }
  HISTORY_DATA = HISTORY_DATA.filter(h => String(h.id) !== String(id));
  return rows[0];
}

/* ===== APP STATE ===== */
const state = { user: null, currentForecast: null, revIsdSeeded: null };

/* ===== HELPERS ===== */
function fmt(n)         { return 'USD ' + Math.round(n).toLocaleString(); }
function fmtDate(s)     { if (!s) return '–'; const d = new Date(s + 'T00:00:00'); return d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}); }
function fmtDateShort(s){ const d = new Date(s + 'T00:00:00'); return d.toLocaleDateString('en-GB',{day:'numeric',month:'short'}); }
function dow(s)         { return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date(s+'T00:00:00').getDay()]; }
function scaledData(routeId, rows = FORECAST_DATA) {
  const sc = ROUTES[routeId]?.scale ?? 1;
  return rows.map(d => ({...d, f:d.f*sc}));
}

/* generated_at is a full ISO timestamp, not the plain YYYY-MM-DD fmtDate takes. */
function fmtTs(ts) {
  if (!ts) return '–';
  return new Date(ts).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
}

/* Quotation timestamps are shown to the client, where "valid until 10 Aug"
   is ambiguous by a whole day — these always carry the time of day. */
function fmtDateTime(ts) {
  if (!ts) return '–';
  const d = new Date(ts);
  return d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}) + ', ' +
         d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',hour12:true});
}

/* Human-facing label for a forecast run, derived from the date its bundle was
   generated: 8 Aug 2026 -> PKL080826. Runs are identified by date rather than
   by the snapshots row id because the row id is an internal detail and means
   nothing to whoever is explaining a revision to a client. */
function pklId(ts) {
  if (!ts) return '–';
  const d = new Date(ts);
  const p = n => String(n).padStart(2, '0');
  return `PKL${p(d.getDate())}${p(d.getMonth() + 1)}${String(d.getFullYear()).slice(-2)}`;
}

const snapshotHeaders = () => ({
  apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
});

/* One row per run day is now enforced at ingest — pkl_to_json.py updates the
   day's existing snapshot instead of appending. This stays for the rows
   written before that, when the workflow re-ran on any .pkl push and the same
   bundle could land several times; those re-ingests would otherwise show up
   as phantom "revisions" with a zero change. Collapse each generated_at day
   to its newest row. Input must be newest-first; output keeps that order. */
function dedupeRuns(rows) {
  const seen = new Set();
  return rows.filter(r => {
    const day = String(r.generated_at).slice(0, 10);
    if (seen.has(day)) return false;
    seen.add(day);
    return true;
  });
}

async function fetchSnapshotIndex() {
  const url = `${SUPABASE_URL}/rest/v1/snapshots?kind=eq.forecast&select=id,generated_at&order=id.desc`;
  const res = await fetch(url, { headers: snapshotHeaders() });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return dedupeRuns(await res.json());
}

/* Payloads are ~90 rows each, so they're fetched by id only once the caller
   knows which runs it actually needs. Returned newest-first. */
async function fetchSnapshotRuns(ids) {
  if (!ids.length) return [];
  const url = `${SUPABASE_URL}/rest/v1/snapshots?id=in.(${ids.join(',')})&select=id,generated_at,payload&order=id.desc`;
  const res = await fetch(url, { headers: snapshotHeaders() });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return (await res.json()).map(r => ({
    id: r.id,
    generatedAt: r.generated_at ?? r.payload?.generated_at,
    forecast: r.payload?.forecast ?? [],
  }));
}

async function loadAllRuns() {
  if (SNAPSHOT_RUNS_LOADED) return SNAPSHOT_RUNS;
  const index = await fetchSnapshotIndex();
  SNAPSHOT_RUNS = await fetchSnapshotRuns(index.map(r => r.id));
  SNAPSHOT_RUNS_LOADED = true;
  return SNAPSHOT_RUNS;
}

function reInitLucide() {
  if (typeof lucide !== 'undefined') lucide.createIcons();
}

/* ===== NAVIGATION ===== */
async function navigateTo(viewId) {
  /* Picking a destination is the end of using the menu, so the drawer closes
     with the choice rather than being left over the page the user just asked
     for. No-op when the sidebar is a permanent rail. */
  closeSidebar();

  document.querySelectorAll('.page').forEach(p => p.classList.add('hidden'));
  document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));

  const page = document.getElementById('page-' + viewId);
  if (page) page.classList.remove('hidden');

  const nav = document.querySelector(`.nav-item[data-view="${viewId}"]`);
  if (nav) nav.classList.add('active');

  /* Header breadcrumb */
  const hl = document.getElementById('header-left');
  if (['forecast-result','client-quote'].includes(viewId) && state.currentForecast) {
    const r = ROUTES[state.currentForecast.routeId];
    hl.innerHTML = `<div class="route-pill">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z"/><circle cx="12" cy="10" r="3"/></svg>
      Route:&nbsp;<strong>${r.label}</strong></div>`;
  } else {
    hl.innerHTML = '';
  }

  if (viewId === 'forecast-result') renderForecastResult();
  if (viewId === 'client-quote')    await renderClientQuote();
  if (viewId === 'history')         renderHistory();
  if (viewId === 'executive')       switchExecTab('forecast');
  /* Re-rendered on every visit rather than initialised once, so a newer
     forecast run is picked up instead of simulating against a stale one. */
  if (viewId === 'market-impact' && window.MarketImpact) MarketImpact.render();

  reInitLucide();
  document.querySelector('.page-area').scrollTop = 0;
}

/* ===== MOBILE NAVIGATION =====
   The sidebar is a fixed rail on wide screens and an off-canvas drawer on
   narrow ones. Which of the two is in play is decided entirely in CSS, so
   nothing here needs to measure the window — this only tracks whether the
   drawer is open, and on desktop that class simply has nothing to do. */
function setSidebarOpen(open) {
  document.getElementById('app-sidebar')?.classList.toggle('open', open);
  document.getElementById('sidebar-backdrop')?.classList.toggle('visible', open);
  document.getElementById('sidebar-toggle')?.setAttribute('aria-expanded', String(open));
  /* Without this the page scrolls under the drawer as the user swipes it. */
  document.body.classList.toggle('nav-open', open);
}

function toggleSidebar() {
  setSidebarOpen(!document.getElementById('app-sidebar')?.classList.contains('open'));
}

function closeSidebar() { setSidebarOpen(false); }

/* Escape closes the drawer, matching every other dismissable layer here. */
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') closeSidebar();
});

/* Widening past the breakpoint turns the drawer back into a permanent rail,
   and the CSS handles that on its own. What it cannot undo is body.nav-open:
   that rule has no breakpoint, so an open drawer left over from a narrow
   window would go on holding the desktop page unscrollable with nothing on
   screen to explain why. The 1024 here is the one in style.css. */
window.addEventListener('resize', () => {
  if (window.innerWidth > 1024) closeSidebar();
});

/* ===== EXECUTIVE DASHBOARD TABS ===== */
function switchExecTab(tab) {
  document.querySelectorAll('.exec-tab').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.execTab === tab);
  });
  document.querySelectorAll('.exec-tab-panel').forEach(panel => {
    panel.classList.toggle('hidden', panel.id !== `exec-tab-panel-${tab}`);
  });
  if (window.ExecPanels) window.ExecPanels.onTabShown(tab);
}

/* ===== AUTH =====
   Real Supabase Auth (email + password). Only @goodfortune.com work
   emails may sign up or sign in — enforced here client-side, and should
   also be locked down in the Supabase dashboard (Auth → Providers →
   Email → restrict allowed email domains) since a client-side check
   alone doesn't stop someone hitting the API directly.

   Sessions are deliberately NOT persisted. Every visit starts at the login
   form and needs an email, a password and a press of Login — a shared
   machine must never open on somebody else's workspace. Turning persistence
   off makes that structural rather than a matter of not calling a restore:
   there is no stored session to come back to. */
const ALLOWED_EMAIL_DOMAIN = '@goodfortune.com';
const sbClient = (SUPABASE_URL && SUPABASE_ANON_KEY && window.supabase)
  ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: { persistSession: false, autoRefreshToken: false },
    })
  : null;

/* Tokens written by an earlier build outlive that build. Nothing reads them
   now, so clear them rather than leaving a live token in storage. */
try {
  Object.keys(localStorage)
    .filter(k => k.startsWith('sb-') && k.endsWith('-auth-token'))
    .forEach(k => localStorage.removeItem(k));
} catch (e) {
  /* storage unavailable — then there was nothing persisted to clean up */
}

function isAllowedEmail(email) {
  return email.endsWith(ALLOWED_EMAIL_DOMAIN);
}

/* Emails are case-insensitive — normalize before validating/sending so
   "Name@GoodFortune.com" and "name@goodfortune.com" are treated (and
   stored) as the same address. */
function normalizeEmail(raw) {
  return raw.trim().toLowerCase();
}

/* Normalizes free-typed names to Title Case regardless of how the user
   typed it ("JOHN DOE" / "john doe" -> "John Doe"), including
   hyphenated/apostrophe'd names ("mary-jane o'brien" -> "Mary-Jane
   O'Brien"). */
function toTitleCase(raw) {
  return raw.trim().replace(/\s+/g, ' ')
    .toLowerCase()
    .replace(/[a-z]+/g, word => word.charAt(0).toUpperCase() + word.slice(1));
}

function setBusy(btn, busy, busyLabel, idleLabel) {
  btn.disabled = busy;
  btn.textContent = busy ? busyLabel : idleLabel;
}

function showAuthMode(mode) {
  document.getElementById('login-mode-signin').classList.toggle('hidden', mode !== 'signin');
  document.getElementById('login-mode-signup').classList.toggle('hidden', mode !== 'signup');
  document.getElementById('login-error').classList.add('hidden');
  document.getElementById('signup-error').classList.add('hidden');
  document.getElementById('signup-success').classList.add('hidden');
}

async function completeLogin(user) {
  state.user = user;
  const displayName = user.user_metadata?.full_name || user.email;
  document.getElementById('header-username').textContent = displayName;
  document.getElementById('view-login').classList.add('hidden');
  const app = document.getElementById('view-app');
  app.classList.remove('hidden');
  app.style.display = 'flex';

  /* defaults */
  const today = new Date().toISOString().slice(0,10);
  document.getElementById('input-isd').value = today;
  applyIsdBounds();

  navigateTo('new-forecast');
}

async function handleLogin(e) {
  e.preventDefault();
  const email = normalizeEmail(document.getElementById('login-email').value);
  const pw    = document.getElementById('login-password').value;
  const err   = document.getElementById('login-error');
  const btn   = document.getElementById('login-submit');

  if (!isAllowedEmail(email)) {
    err.textContent = `Please use your ${ALLOWED_EMAIL_DOMAIN} work email.`;
    err.classList.remove('hidden');
    return;
  }
  if (!pw) {
    err.textContent = 'Please enter your password.';
    err.classList.remove('hidden');
    return;
  }
  if (!sbClient) {
    err.textContent = 'Auth is not configured. Contact an administrator.';
    err.classList.remove('hidden');
    return;
  }
  err.classList.add('hidden');

  setBusy(btn, true, 'Signing in…', 'Login');
  const { data, error } = await sbClient.auth.signInWithPassword({ email, password: pw });
  setBusy(btn, false, 'Signing in…', 'Login');

  if (error) {
    err.textContent = error.message || 'Invalid email or password.';
    err.classList.remove('hidden');
    return;
  }

  await completeLogin(data.user);
}

async function handleSignup(e) {
  e.preventDefault();
  const name    = toTitleCase(document.getElementById('signup-name').value);
  const email   = normalizeEmail(document.getElementById('signup-email').value);
  const pw      = document.getElementById('signup-password').value;
  const pwAgain = document.getElementById('signup-password-confirm').value;
  const err     = document.getElementById('signup-error');
  const ok      = document.getElementById('signup-success');
  const btn     = document.getElementById('signup-submit');

  ok.classList.add('hidden');

  if (!name) {
    err.textContent = 'Please enter your full name.';
    err.classList.remove('hidden');
    return;
  }
  if (!isAllowedEmail(email)) {
    err.textContent = `Please use your ${ALLOWED_EMAIL_DOMAIN} work email.`;
    err.classList.remove('hidden');
    return;
  }
  if (pw.length < 8) {
    err.textContent = 'Password must be at least 8 characters.';
    err.classList.remove('hidden');
    return;
  }
  if (pw !== pwAgain) {
    err.textContent = 'Passwords do not match.';
    err.classList.remove('hidden');
    return;
  }
  if (!sbClient) {
    err.textContent = 'Auth is not configured. Contact an administrator.';
    err.classList.remove('hidden');
    return;
  }
  err.classList.add('hidden');

  setBusy(btn, true, 'Creating account…', 'Create account');
  const { data, error } = await sbClient.auth.signUp({
    email, password: pw,
    options: { data: { full_name: name } },
  });
  setBusy(btn, false, 'Creating account…', 'Create account');

  if (error) {
    err.textContent = error.message || 'Could not create account.';
    err.classList.remove('hidden');
    return;
  }

  if (data.session) {
    await completeLogin(data.user);
    return;
  }

  /* Email confirmation is required before a session exists. */
  ok.textContent = 'Account created. Check your email to confirm it, then sign in.';
  ok.classList.remove('hidden');
  document.getElementById('signup-form').reset();
}

async function handleForgotPassword() {
  const email = document.getElementById('login-email').value.trim();
  const err   = document.getElementById('login-error');

  if (!isAllowedEmail(email)) {
    err.textContent = `Enter your ${ALLOWED_EMAIL_DOMAIN} email above first, then click "Forgot password?".`;
    err.classList.remove('hidden');
    return;
  }
  if (!sbClient) {
    err.textContent = 'Auth is not configured. Contact an administrator.';
    err.classList.remove('hidden');
    return;
  }

  const { error } = await sbClient.auth.resetPasswordForEmail(email);
  err.textContent = error ? (error.message || 'Could not send reset email.') : 'Password reset email sent — check your inbox.';
  err.classList.remove('hidden');
}

async function handleLogout() {
  if (sbClient) await sbClient.auth.signOut();
  document.getElementById('view-app').style.display = '';
  document.getElementById('view-app').classList.add('hidden');
  document.getElementById('view-login').classList.remove('hidden');
  showAuthMode('signin');
  document.getElementById('login-form').reset();
  state.user = null;
  state.currentForecast = null;
}

function togglePw(inputId, btn) {
  const inp = document.getElementById(inputId);
  inp.type = inp.type === 'password' ? 'text' : 'password';
}

function toggleUserMenu() {
  document.getElementById('user-menu').classList.toggle('hidden');
}
document.addEventListener('click', e => {
  const m = document.getElementById('user-menu');
  if (m && !e.target.closest('.header-user')) m.classList.add('hidden');
});

/* Lock the ISD input to the forecast data range and clamp its value */
function applyIsdBounds() {
  const isdEl = document.getElementById('input-isd');
  if (!isdEl || !FORECAST_DATA.length) return;
  const minDate = FORECAST_DATA[0].date;
  const maxDate = FORECAST_DATA[FORECAST_DATA.length - 1].date;
  isdEl.min = minDate;
  isdEl.max = maxDate;
  if (!isdEl.value || isdEl.value < minDate) isdEl.value = minDate;
  else if (isdEl.value > maxDate)            isdEl.value = maxDate;
}

/* ===== NEW FORECAST ===== */
function handleForecast() {
  const routeId       = document.getElementById('input-route')?.value || FIXED_ROUTE;
  const isdDate       = document.getElementById('input-isd').value;
  const containersRaw = document.getElementById('input-containers').value;
  const containers    = parseInt(containersRaw);
  const company       = document.getElementById('input-company').value.trim();
  const pic           = document.getElementById('input-pic').value.trim();

  if (!isdDate)                        { alert('Please select an Intended Ship Date.');     return; }
  if (!containersRaw || containers < 1) { alert('Please enter the number of containers.');   return; }
  if (!company)                        { alert('Please enter the Company Name.');           return; }
  if (!pic)                            { alert('Please enter the Person in Charge (PIC).'); return; }

  const minDate = FORECAST_DATA[0].date;
  const maxDate = FORECAST_DATA[FORECAST_DATA.length - 1].date;
  if (isdDate < minDate || isdDate > maxDate) {
    alert(`Intended Ship Date must be between ${fmtDate(minDate)} and ${fmtDate(maxDate)}.`);
    return;
  }

  const data = scaledData(routeId);

  /* Find closest available data point to ISD */
  let isdRow = data.find(d => d.date === isdDate);
  if (!isdRow) {
    isdRow = data.reduce((best, d) =>
      Math.abs(new Date(d.date) - new Date(isdDate)) <
      Math.abs(new Date(best.date) - new Date(isdDate)) ? d : best, data[0]);
  }

  /* ±5 day window */
  const isdIdx  = data.indexOf(isdRow);
  const wStart  = Math.max(0, isdIdx - 5);
  const wEnd    = Math.min(data.length - 1, isdIdx + 5);
  const dayWindow = data.slice(wStart, wEnd + 1);

  const lowestRow = dayWindow.reduce((mn, d) => d.f < mn.f ? d : mn, dayWindow[0]);

  state.currentForecast = {
    routeId, isdDate: isdRow.date, containers, company, pic,
    isdRow, lowestRow, dayWindow, allData: data,
    /* The date the client asked for. The lowest nearby date is shown
       alongside it as information the analyst can offer, but it is never
       applied automatically — the shipping date is the client's call. */
    clientDate: isdRow.date,
    pendingId: null, /* set when Client Quote page is first opened */
  };

  /* Feeds the Executive Dashboard's unified selectedISD (shared with its
     own "View Forecast for Date" picker) so a date chosen here shows up
     there automatically. */
  if (window.ExecData) ExecData.setSelectedISD(isdRow.date);

  /* The forecast figures come first. The user reviews the day grid and the
     lowest nearby fee here, then commits to a quote from this page via
     "Prepare Client Quote". */
  navigateTo('forecast-result');
}

/* ===== FORECAST RESULT ===== */
function renderForecastResult() {
  const cf = state.currentForecast;
  if (!cf) return;

  document.getElementById('res-route').textContent = ROUTES[cf.routeId].label;
  document.getElementById('res-isd').textContent   = fmtDate(cf.isdDate);
  document.getElementById('res-qty').textContent   = cf.containers + ' FEU';

  /* Day grid */
  const grid = document.getElementById('day-grid');
  grid.innerHTML = cf.dayWindow.map(d => {
    const isSel    = d.date === cf.isdDate;
    const isLowest = d.date === cf.lowestRow.date && d.date !== cf.isdDate;
    return `<div class="day-card${isSel ? ' selected' : ''}${isLowest ? ' lowest' : ''}">
      ${isLowest ? '<div class="day-lowest-badge">Lowest</div>' : ''}
      <div class="day-dow">${dow(d.date)}</div>
      <div class="day-date">${fmtDateShort(d.date)}</div>
      ${isSel ? '<div class="day-sel-label">(Selected)</div>' : ''}
      <div class="day-usd-label">USD</div>
      <div class="day-fee-val">${Math.round(d.f).toLocaleString()}</div>
    </div>`;
  }).join('');

  /* Summary cards — fees are total (rate × containers) */
  const isdTotal = cf.isdRow.f    * cf.containers;
  const lowTotal = cf.lowestRow.f * cf.containers;

  document.getElementById('sel-date').textContent = fmtDate(cf.isdDate);
  document.getElementById('sel-fee').textContent  = fmt(isdTotal);

  document.getElementById('low-date').textContent = fmtDate(cf.lowestRow.date);
  document.getElementById('low-fee').textContent  = fmt(lowTotal);

  cf.revision = buildRevision(cf);
  renderRevision(cf.revision);

  const saving    = isdTotal - lowTotal;
  const savingPct = ((saving / isdTotal) * 100).toFixed(1);
  if (saving <= 0) {
    document.getElementById('saving-val').textContent = 'Best Rate';
    document.getElementById('saving-pct').textContent = 'Your selected date is already the lowest';
  } else {
    document.getElementById('saving-val').textContent = fmt(saving);
    document.getElementById('saving-pct').textContent = `${savingPct}% less`;
  }
}

/* ===== FORECAST REVISION (latest run vs. immediately previous run) =====
   Compares like for like: same route, same intended ship date, latest
   snapshot against the one before it. Deliberately NOT compared against the
   lowest nearby date, another ISD, or another request — those are different
   questions and are answered elsewhere on this page. */
function buildRevision(cf) {
  if (!PREV_FORECAST_DATA.length) return null;

  /* Same route (same scale) and same date. If the previous run's horizon
     didn't reach this ISD there is nothing to compare against. */
  const prevRow = scaledData(cf.routeId, PREV_FORECAST_DATA).find(d => d.date === cf.isdDate);
  if (!prevRow) return null;

  const perFeu = cf.isdRow.f - prevRow.f;
  const total  = perFeu * cf.containers;

  return {
    prevFee: prevRow.f,
    latestFee: cf.isdRow.f,
    perFeu,
    pct: (perFeu / prevRow.f) * 100,
    total,
    latestAt: FORECAST_META.generatedAt,
    prevAt: PREV_FORECAST_META.generatedAt,
    /* Rounded, so sub-dollar drift on the displayed total reads as "no change"
       rather than an arrow pointing at an invisible difference. */
    dir: Math.round(total) === 0 ? 'flat' : (total > 0 ? 'up' : 'down'),
  };
}

function renderRevision(rev) {
  const el = document.getElementById('sel-revision');
  if (!el) return;

  if (!rev) {
    el.innerHTML = '<div class="rev-line rev-flat">First available forecast</div>';
    return;
  }

  const arrow = { up: '&uarr;', down: '&darr;', flat: '&mdash;' }[rev.dir];
  const body  = rev.dir === 'flat'
    ? 'No change vs previous forecast'
    : `${fmt(Math.abs(rev.total))} (${rev.perFeu > 0 ? '+' : '−'}${Math.abs(rev.pct).toFixed(2)}%) vs previous forecast`;

  el.innerHTML =
    `<div class="rev-line rev-${rev.dir}"><span class="rev-arrow">${arrow}</span> ${body}</div>
     <div class="rev-meta">Updated ${fmtTs(rev.latestAt)} &middot;
       <button type="button" class="rev-link" onclick="openRevisionModal()">View details</button>
     </div>`;
}

/* USD with cents — the per-FEU difference is where the change actually
   originates, so rounding it to whole dollars here would make the headline
   figures look like they don't reconcile. */
function fmt2(n) {
  return 'USD ' + Math.abs(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function openRevisionModal() {
  const cf  = state.currentForecast;
  const rev = cf?.revision;
  if (!rev) return;

  const qty  = cf.containers;
  const sign = rev.perFeu > 0 ? '+' : (rev.perFeu < 0 ? '−' : '');
  const word = rev.dir === 'up' ? 'Increase' : rev.dir === 'down' ? 'Decrease' : 'Change';

  const tr = (label, prev, latest) =>
    `<tr><td>${label}</td><td>${prev}</td><td class="rev-latest-col">${latest}</td></tr>`;

  document.getElementById('revision-modal-body').innerHTML = `
    <table class="rev-table">
      <thead><tr><th>Comparison</th><th>Previous</th><th>Latest</th></tr></thead>
      <tbody>
        ${tr('Forecast generated', pklId(rev.prevAt), pklId(rev.latestAt))}
        ${tr('', `<span class="rev-subtle">${fmtTs(rev.prevAt)}</span>`, `<span class="rev-subtle">${fmtTs(rev.latestAt)}</span>`)}
        ${tr('Fee per FEU', fmt(rev.prevFee), fmt(rev.latestFee))}
        ${tr(`Total for ${qty} FEU`, fmt(rev.prevFee * qty), fmt(rev.latestFee * qty))}
      </tbody>
    </table>

    <div class="rev-summary">
      <div class="rev-row">
        <span>${word} per FEU</span>
        <span class="rev-${rev.dir}">${sign}${fmt2(rev.perFeu)} (${sign}${Math.abs(rev.pct).toFixed(2)}%)</span>
      </div>
      <div class="rev-row">
        <span>Total impact for ${qty} FEU</span>
        <span class="rev-${rev.dir} rev-total">${sign}${fmt(Math.abs(rev.total))}</span>
      </div>
    </div>

    <p class="rev-explain">This prediction was revised after a newer market-data update became available.</p>

    <button type="button" class="btn-secondary btn-full" onclick="openRevisionFullHistory()">
      <i data-lucide="history" style="width:15px;height:15px;"></i>
      View Full History
    </button>`;

  document.getElementById('revision-modal').classList.remove('hidden');
  reInitLucide();
}

/* Jumps from the modal into the Forecast Revisions tab, pre-filtered to the
   same route and shipment date so the full run-by-run trail is one click
   away from the two-run summary. */
async function openRevisionFullHistory() {
  const cf = state.currentForecast;
  closeRevisionModal();

  /* Filters are set before navigating: the inputs live in the DOM whether or
     not the page is visible, and navigateTo re-renders whichever history tab
     is showing — so seeding them first avoids a throwaway render on the
     previous selection. */
  if (cf) {
    const routeEl = document.getElementById('rev-route');
    const isdEl   = document.getElementById('rev-isd');
    if (routeEl) routeEl.value = cf.routeId;
    if (isdEl)   isdEl.value   = cf.isdDate;
    state.revIsdSeeded = cf.isdDate;
  }

  await navigateTo('history');
  switchHistoryTab('revisions');
}

function closeRevisionModal() {
  document.getElementById('revision-modal').classList.add('hidden');
}

/* ===== CLIENT QUOTE =====
   Two states live on this page:

     working  — nothing issued yet. Every figure is recomputed from the
                latest forecast and the date picker moves the price freely.
                Only reached now when issuing failed, or on a record whose
                decision was recorded before quotations were issued at all.
     issued   — a reference and validity window exist. The price the client
                was given is frozen on the quote_requests row and rendered
                from there, so a newer forecast run cannot move it. Expiry
                does NOT unfreeze it.

   The move from working to issued needs no button press: opening this
   preview for a pending record issues the quotation. Reaching this page
   means a forecast was generated for a named company and PIC, which is the
   decision to quote them.

   What is locked is the issued document, never the client's choice: the
   date picker stays open in both states. Changing the date after a
   quotation has gone out issues a new one for the new date (see
   selectClientDate/requoteForDate), exactly as re-quoting after expiry
   does (regenerateQuotation). The quoted shipping date is the client's
   decision; the lowest nearby date is shown as information, never applied
   on their behalf.

   Nothing on this page or in the exported PDF is internal-only: the
   previous forecast, the day-on-day revision, and the run-by-run history
   deliberately stay on the Forecast Result page and the History view. */
const MARKUP = 1.20;
const QUOTE_VALIDITY_HOURS = 48;

/* The quote_requests row backing the open preview, if any. */
function currentQuoteRecord() {
  const id = state.currentForecast?.pendingId;
  return id ? HISTORY_DATA.find(h => String(h.id) === String(id)) : null;
}

function isIssued(rec)  { return !!(rec && rec.issuedAt); }
function isExpired(rec) { return isIssued(rec) && new Date(rec.validUntil).getTime() <= Date.now(); }

/* SSQ-YYYYMMDD-#### — issue date in the user's own timezone (the date the
   client sees on the document) plus the server-assigned row id, which is
   what makes it unique. */
function quoteRefFor(id, issuedAt) {
  const d = new Date(issuedAt);
  const ymd = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
  return `SSQ-${ymd}-${String(id).padStart(4, '0')}`;
}

/* Single source for every figure the page renders, so the working and
   issued states can't drift apart in one panel but not another. */
function quoteFigures(cf, rec) {
  const issued  = isIssued(rec);
  const qty     = cf.containers;
  const isdFee  = issued ? rec.isdFee  : cf.isdRow.f;
  const lowFee  = issued ? rec.lowFee  : cf.lowestRow.f;
  const lowDate = issued ? rec.lowDate : cf.lowestRow.date;

  const clientDate = issued ? rec.clientDate : (cf.clientDate || cf.isdDate);
  const clientFee  = issued
    ? rec.quotedFee
    : (cf.allData.find(d => d.date === clientDate) || cf.isdRow).f;

  return {
    issued, qty, isdFee, lowFee, lowDate, clientDate, clientFee,
    isdShip: isdFee * qty, isdQuote: isdFee * qty * MARKUP,
    lowShip: lowFee * qty, lowQuote: lowFee * qty * MARKUP,
    clientShip: clientFee * qty,
    /* The issued total is read back rather than recomputed: it is the
       number on the client's document, not a formula's current output. */
    clientTotal: issued ? rec.quotedPrice : clientFee * qty * MARKUP,
    forecastAt: issued ? rec.forecastGeneratedAt : FORECAST_META.generatedAt,
  };
}

async function renderClientQuote() {
  const cf = state.currentForecast;
  if (!cf) return;

  document.getElementById('cq-route').textContent = ROUTES[cf.routeId].label;
  document.getElementById('cq-isd').textContent   = fmtDate(cf.isdDate);
  document.getElementById('cq-qty').textContent   = cf.containers + ' FEU';

  /* Saving the record and issuing the quotation used to both fire silently
     on open. They are now two separate, deliberate presses — see
     saveForecastRecord() and issueQuotationNow(). The gap between them is
     what gives a saved request a life of its own before it hardens into a
     priced document: while it sits there un-issued it can still be edited or
     deleted from Forecast History, which is impossible once a price has
     gone to the client. */
  const rec = currentQuoteRecord();

  const f = quoteFigures(cf, rec);
  if (f.issued) cf.clientDate = f.clientDate;

  const saving = f.isdQuote - f.lowQuote;
  const savPct = f.isdQuote !== 0 ? ((saving / f.isdQuote) * 100).toFixed(2) : '0.00';

  /* KPI cards */
  document.getElementById('kpi-isd-quote').textContent  = fmt(f.isdQuote);
  document.getElementById('kpi-isd-sub').textContent    = 'ISD: ' + fmtDate(cf.isdDate);
  document.getElementById('kpi-low-quote').textContent  = fmt(f.lowQuote);
  /* Advisory only — naming the date makes clear it's an option to offer,
     not the date being quoted. */
  document.getElementById('kpi-low-sub').textContent    =
    f.lowDate === cf.isdDate ? `${fmtDate(f.lowDate)} — already the lowest`
                             : `${fmtDate(f.lowDate)} — available if the client prefers`;
  document.getElementById('kpi-saving').textContent     = fmt(saving);
  document.getElementById('kpi-saving-pct').textContent = saving <= 0
    ? 'Requested ISD is already the lowest'
    : `-${savPct}% if the client moves to ${fmtDateShort(f.lowDate)}`;

  /* Table headers */
  document.getElementById('th-isd').textContent = `Selected ISD (${fmtDate(cf.isdDate)})`;
  document.getElementById('th-low').textContent = `Lowest Nearby Date (${fmtDate(f.lowDate)})`;

  /* Comparison rows */
  document.getElementById('ct-isd-fee').textContent    = fmt(f.isdShip);
  document.getElementById('ct-low-fee').textContent    = fmt(f.lowShip);
  document.getElementById('ct-isd-quote').textContent  = fmt(f.isdQuote);
  document.getElementById('ct-low-quote').textContent  = fmt(f.lowQuote);
  document.getElementById('ct-isd-markup').textContent = fmt(f.isdShip * 0.20);
  document.getElementById('ct-low-markup').textContent = fmt(f.lowShip * 0.20);

  /* Cost difference — shipping fee gap between the two dates (pre-markup) */
  const costDiff    = f.isdShip - f.lowShip;
  const costDiffPct = f.isdShip !== 0 ? ((costDiff / f.isdShip) * 100).toFixed(2) : '0.00';
  document.getElementById('ct-isd-costdiff').textContent = 'Baseline';
  document.getElementById('ct-low-costdiff').textContent = costDiff <= 0
    ? `${fmt(Math.abs(costDiff))} higher`
    : `-${fmt(costDiff)} (-${costDiffPct}%)`;

  /* Potential saving — quotation price gap (post-markup) */
  document.getElementById('ct-isd-saving').textContent = 'Baseline';
  document.getElementById('ct-low-saving').textContent = saving <= 0
    ? 'No additional saving'
    : `-${fmt(saving)} (-${savPct}%)`;

  /* Client date calendar picker — always usable. The shipping date is the
     client's decision, so it stays open even after a quotation is issued;
     moving it re-quotes rather than editing the issued document (see
     selectClientDate). */
  cf.clientDate = f.clientDate;
  initClientDateCalendar(cf.clientDate);
  document.getElementById('client-date-sub').textContent = f.issued
    ? 'Changing the date issues a new quotation'
    : 'Select Date from Forecast Range';

  renderQuotationDoc(cf, rec);

  /* Show the recorded status if this is a history record, otherwise reset */
  const currentStatus = rec?.status || 'Pending';
  const statusEl      = document.getElementById('decision-status-text');
  statusEl.textContent = currentStatus;
  statusEl.className   = currentStatus === 'Confirmed' ? 'status-confirmed'
                       : currentStatus === 'Cancelled'  ? 'status-cancelled'
                       : 'status-pending';

  /* Button states. A decision can only be recorded against a quotation the
     client was actually given, so Record/Export wait for the issue. */
  const expired  = isExpired(rec);
  const regenBtn = document.getElementById('regen-btn');
  const btn      = document.getElementById('record-btn');
  const expBtn   = document.getElementById('export-btn');

  const canRegen = expired && currentStatus === 'Pending';
  regenBtn.classList.toggle('hidden', !canRegen);
  regenBtn.disabled = !canRegen;

  if (currentStatus === 'Pending') {
    btn.disabled = !f.issued;
    btn.style.opacity = f.issued ? '' : '0.65';
    btn.innerHTML = `<i data-lucide="clipboard-check" style="width:16px;height:16px;"></i> Record Client Choice`;
  } else {
    btn.disabled = true;
    btn.style.opacity = '0.65';
    btn.textContent = currentStatus === 'Confirmed' ? 'Choice Recorded' : 'Quote Cancelled';
  }

  expBtn.disabled = !f.issued;
  expBtn.style.opacity = f.issued ? '' : '0.65';

  renderClientTotals(f);
  reInitLucide();
}

/* Right-hand fee breakdown. Reads from quoteFigures so an issued quote
   shows the frozen total rather than today's forecast. */
function renderClientTotals(f) {
  document.getElementById('cd-fee').textContent    = fmt(f.clientShip);
  document.getElementById('cd-markup').textContent = fmt(f.clientShip * 0.20);
  document.getElementById('cd-total').textContent  = fmt(f.clientTotal);
}

/* Re-prices the working (not yet issued) quote as the date moves. Once a
   quotation exists, selectClientDate() routes to requoteForDate() instead —
   this guard is here so no other caller can quietly re-price an issued
   document. */
function updateClientQuote(selDate) {
  const cf = state.currentForecast;
  if (!cf) return;
  if (isIssued(currentQuoteRecord())) return;

  selDate = selDate || cf.clientDate || cf.isdDate;
  cf.clientDate = selDate;
  renderClientTotals(quoteFigures(cf, null));
}

/* ===== QUOTATION DOCUMENT (reference / issue / validity) =====
   The client-facing identity of the quote. Rendered on the preview and
   reproduced verbatim in the PDF so the two can never disagree. */
/* Carries only what the fields above it don't. The expiry is stated as a
   duration, not repeated as a date, because Valid Until sits directly above
   with the same timestamp. What's left is genuinely new: the shipping date
   being quoted (the client's choice, so it moves with the date picker) and
   the forecast run the price came from (fixed until a newer run lands). */
function validityStatement(f) {
  return `For shipment on ${fmtDate(f.clientDate)}, priced from market information of ` +
         `${fmtTs(f.forecastAt)} and held for ${QUOTE_VALIDITY_HOURS} hours from issue. ` +
         `Rates may be revised after that.`;
}

function renderQuotationDoc(cf, rec) {
  const el = document.getElementById('quote-doc');
  if (!el) return;

  /* Expiry can arrive while the page is just sitting open, so re-render at
     the moment it does rather than leaving a stale "Valid" badge up until
     the next navigation. */
  clearTimeout(state.quoteExpiryTimer);
  if (isIssued(rec) && !isExpired(rec)) {
    const ms = new Date(rec.validUntil).getTime() - Date.now();
    if (ms > 0 && ms < 2147483647) {
      state.quoteExpiryTimer = setTimeout(() => renderClientQuote(), ms + 1000);
    }
  }

  /* Three states before a quotation exists, and they are genuinely different
     situations rather than shades of the same one: nothing saved at all, a
     saved request awaiting a price, and a save that went through but whose
     issue attempt failed. Each carries its own next action. */
  if (!rec) {
    el.className = 'quote-doc quote-doc-draft';
    el.innerHTML =
      `<div class="qd-row">
         <div class="qd-title">This forecast has not been saved yet</div>
         <span class="qd-badge qd-badge-draft">Unsaved</span>
       </div>
       <p class="qd-note">Nothing has been written to Forecast History. The figures below follow the
         latest forecast and will keep moving with it. Saving files this request under
         ${cf.company} so it can be found, edited or removed later.</p>
       <button type="button" class="btn-primary qd-action" onclick="saveForecastRecord()">
         Save Forecast Record
       </button>`;
    return;
  }

  if (!isIssued(rec)) {
    el.className = 'quote-doc quote-doc-draft';
    el.innerHTML =
      `<div class="qd-row">
         <div class="qd-title">${state.quoteIssueFailed
            ? 'Quotation could not be generated'
            : 'Saved — no quotation issued yet'}</div>
         <span class="qd-badge qd-badge-draft">${state.quoteIssueFailed ? 'Not issued' : 'Draft'}</span>
       </div>
       <p class="qd-note">${state.quoteIssueFailed
          ? 'The request is saved, but no price has been fixed for this client. Check your connection and try again.'
          : `The request is saved and still fully editable from Forecast History. Issuing stamps a
             reference, fixes the price for ${QUOTE_VALIDITY_HOURS} hours and closes the record to
             further edits — so it is the point of no return, not a formality.`}</p>
       <button type="button" class="btn-primary qd-action" onclick="issueQuotationNow()">
         ${state.quoteIssueFailed ? 'Try Again' : 'Generate Quotation'}
       </button>`;
    return;
  }

  const f       = quoteFigures(cf, rec);
  const expired = isExpired(rec);

  el.className = 'quote-doc' + (expired ? ' quote-doc-expired' : '');
  el.innerHTML =
    `<div class="qd-row">
       <div>
         <div class="qd-label">Quotation Reference</div>
         <div class="qd-ref">${rec.quoteRef}</div>
       </div>
       <span class="qd-badge ${expired ? 'qd-badge-expired' : 'qd-badge-valid'}">
         ${expired ? 'Expired' : 'Valid'}
       </span>
     </div>
     <div class="qd-grid">
       <div><div class="qd-label">Issued</div><div class="qd-val">${fmtDateTime(rec.issuedAt)}</div></div>
       <div><div class="qd-label">Valid Until</div><div class="qd-val">${fmtDateTime(rec.validUntil)}</div></div>
       <div><div class="qd-label">Quoted Price</div><div class="qd-val qd-price">${fmt(rec.quotedPrice)}</div></div>
     </div>
     <p class="qd-note">${validityStatement(f)}</p>
     ${expired
       ? `<p class="qd-note qd-note-expired">This quotation has passed its validity period. The price above
            stays on record as issued — generate a new quotation to quote from the latest forecast.</p>`
       : ''}`;
}

/* Issues the open preview: stamps the reference and validity window and
   freezes the price, the quoted date, and the forecast run behind them.

   Throws rather than alerting on failure, leaving its callers to decide how
   loudly to complain — issueQuotationNow() re-renders into the retry state,
   requoteForDate() and regenerateQuotation() surface their own messages. */
async function issueQuotationFor(cf, rec) {
  if (!cf || !rec || isIssued(rec)) return;   /* already locked — never re-price */

  const issuedAt   = new Date();
  const validUntil = new Date(issuedAt.getTime() + QUOTE_VALIDITY_HOURS * 3600 * 1000);
  const clientDate = cf.clientDate || cf.isdDate;
  const clientFee  = (cf.allData.find(d => d.date === clientDate) || cf.isdRow).f;

  await updateHistoryRecord(rec.id, {
    clientDate,
    /* Re-stamped from what is on screen right now: the Pending row was
       written when the page opened, which in a long session may predate
       the forecast run this price actually comes from. */
    isdFee: cf.isdRow.f,
    lowDate: cf.lowestRow.date,
    lowFee: cf.lowestRow.f,
    quoteRef: quoteRefFor(rec.id, issuedAt),
    issuedAt: issuedAt.toISOString(),
    validUntil: validUntil.toISOString(),
    quotedFee: clientFee,
    quotedPrice: clientFee * cf.containers * MARKUP,
    forecastGeneratedAt: FORECAST_META.generatedAt,
  });
}

/* ===== CREATE =====
   Writes the forecast currently on screen into quote_requests as a Pending,
   un-issued request. This is the C of the CRUD set and the only place a
   record is born from the normal workflow.

   It stops at saving. No price is fixed here, which is the whole point: the
   record spends its first life editable and deletable, and only hardens when
   someone chooses to issue it. */
async function saveForecastRecord() {
  const cf = state.currentForecast;
  if (!cf || cf.pendingId) return;

  try {
    const saved = await insertHistoryRecord({
      company: cf.company,
      pic: cf.pic,
      route: cf.routeId,
      isdDate: cf.isdDate,
      containers: cf.containers,
      isdFee: cf.isdRow.f,
      lowDate: cf.lowestRow.date,
      lowFee: cf.lowestRow.f,
      clientDate: cf.clientDate || cf.isdDate,
    });
    cf.pendingId = saved.id;
  } catch (e) {
    console.error('Failed to save the forecast record:', e);
    alert('Could not save this forecast record. Please check your connection and try again.');
    return;
  }

  await renderClientQuote();
}

/* Issues the saved request, on an explicit press. Failure is recorded on
   state rather than alerted, so the page redraws into its retry state with
   the working figures still readable underneath. */
async function issueQuotationNow() {
  const cf  = state.currentForecast;
  const rec = currentQuoteRecord();
  if (!cf || !rec || isIssued(rec) || rec.status !== 'Pending') return;

  state.quoteIssueFailed = false;
  try {
    await issueQuotationFor(cf, rec);
  } catch (e) {
    console.error('Failed to issue quotation:', e);
    state.quoteIssueFailed = true;
  }
  await renderClientQuote();
}

/* Re-quotes an expired quotation from the latest forecast as a brand-new
   record with its own reference. The expired one is left untouched — it is
   the record of what the client was told. */
async function regenerateQuotation() {
  const cf = state.currentForecast;
  if (!cf) return;
  const rec = currentQuoteRecord();
  if (!isExpired(rec) || rec.status !== 'Pending') return;

  const btn = document.getElementById('regen-btn');
  btn.disabled = true;

  /* Latest forecast, same request: same route, ISD and quantity, with the
     ±5 day window and its lowest date recomputed from current data. */
  const data   = scaledData(cf.routeId);
  const isdRow = data.find(d => d.date === cf.isdDate) ||
    data.reduce((best, d) =>
      Math.abs(new Date(d.date) - new Date(cf.isdDate)) <
      Math.abs(new Date(best.date) - new Date(cf.isdDate)) ? d : best, data[0]);
  const isdIdx    = data.indexOf(isdRow);
  const dayWindow = data.slice(Math.max(0, isdIdx - 5), Math.min(data.length - 1, isdIdx + 5) + 1);
  const lowestRow = dayWindow.reduce((mn, d) => d.f < mn.f ? d : mn, dayWindow[0]);

  try {
    const fresh = await insertHistoryRecord({
      company: cf.company, pic: cf.pic, route: cf.routeId,
      isdDate: isdRow.date, containers: cf.containers,
      isdFee: isdRow.f, lowDate: lowestRow.date, lowFee: lowestRow.f,
      /* Carries the date the client had settled on, not the newly cheapest
         one — re-quoting after expiry re-prices the same shipment, it
         doesn't silently move the shipping date. */
      clientDate: cf.clientDate || isdRow.date,
    });
    state.currentForecast = {
      ...cf, isdDate: isdRow.date, isdRow, lowestRow, dayWindow, allData: data,
      clientDate: cf.clientDate || isdRow.date, pendingId: fresh.id,
    };
  } catch (e) {
    console.error('Failed to start a new quotation:', e);
    alert('Could not start a new quotation. Please check your connection and try again.');
    btn.disabled = false;
    return;
  }

  /* Re-quoting is one continuous act from the user's side — they asked for a
     fresh price, not for a draft to then issue by hand — so the new record is
     issued straight away rather than left sitting in the draft state. */
  await issueQuotationNow();
}

/* ===== CLIENT DATE CALENDAR PICKER =====
   Only dates present in the 90-day forecast range (cf.allData) are
   selectable — everything else is rendered disabled. */
function toISODate(d) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function initClientDateCalendar(selDate) {
  const d = new Date(selDate + 'T00:00:00');
  state.clientCalMonth = new Date(d.getFullYear(), d.getMonth(), 1);
  document.getElementById('client-date-label').textContent = fmtDate(selDate);
  renderClientDateCalendar();
}

function shiftClientDateMonth(delta) {
  const m = state.clientCalMonth;
  state.clientCalMonth = new Date(m.getFullYear(), m.getMonth() + delta, 1);
  renderClientDateCalendar();
}

function renderClientDateCalendar() {
  const cf = state.currentForecast;
  if (!cf || !state.clientCalMonth) return;

  const monthStart  = state.clientCalMonth;
  const validDates  = new Set(cf.allData.map(d => d.date));
  const minDate     = cf.allData[0].date;
  const maxDate     = cf.allData[cf.allData.length - 1].date;

  document.getElementById('client-date-month-label').textContent =
    monthStart.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });

  const prevMonthEnd   = new Date(monthStart.getFullYear(), monthStart.getMonth(), 0);
  const nextMonthStart = new Date(monthStart.getFullYear(), monthStart.getMonth() + 1, 1);
  document.getElementById('client-date-prev').disabled = toISODate(prevMonthEnd)   < minDate;
  document.getElementById('client-date-next').disabled = toISODate(nextMonthStart) > maxDate;

  const grid = document.getElementById('client-date-grid');
  grid.innerHTML = '';

  const firstDow     = monthStart.getDay();
  const daysInMonth  = new Date(monthStart.getFullYear(), monthStart.getMonth() + 1, 0).getDate();

  for (let i = 0; i < firstDow; i++) {
    grid.insertAdjacentHTML('beforeend', '<span class="date-picker-day empty"></span>');
  }
  for (let day = 1; day <= daysInMonth; day++) {
    const iso       = toISODate(new Date(monthStart.getFullYear(), monthStart.getMonth(), day));
    const inRange   = validDates.has(iso);
    const isSel     = iso === cf.clientDate;
    const isLowest  = iso === cf.lowestRow.date;
    grid.insertAdjacentHTML('beforeend',
      `<button type="button" class="date-picker-day${isSel ? ' selected' : ''}${isLowest ? ' lowest' : ''}"` +
      `${inRange ? '' : ' disabled'} onclick="selectClientDate('${iso}')">${day}</button>`);
  }
}

function toggleClientDateCalendar() {
  document.getElementById('client-date-panel').classList.toggle('hidden');
}

/* The shipping date belongs to the client, so the picker never locks. What
   is locked is the issued document: moving the date after a quotation has
   gone out doesn't rewrite that quotation's price, it issues a new one for
   the new date and leaves the old on record. Confirmed first, so browsing
   dates can't quietly mint a trail of references. */
async function selectClientDate(iso) {
  const cf = state.currentForecast;
  if (!cf) return;
  document.getElementById('client-date-panel').classList.add('hidden');

  const rec = currentQuoteRecord();
  if (isIssued(rec)) {
    if (iso === rec.clientDate) return;

    if (rec.status !== 'Pending') {
      alert(`Quotation ${rec.quoteRef} already has the client's decision recorded, so it can't be re-quoted. ` +
            `Start a new forecast to quote a different date.`);
      return;
    }
    const ok = confirm(
      `Quotation ${rec.quoteRef} was issued for ${fmtDate(rec.clientDate)} at ${fmt(rec.quotedPrice)}.\n\n` +
      `Quoting ${fmtDate(iso)} instead issues a NEW quotation with its own reference and validity period. ` +
      `${rec.quoteRef} stays on record unchanged.\n\nContinue?`);
    if (!ok) return;

    await requoteForDate(iso);
    return;
  }

  updateClientQuote(iso);
  document.getElementById('client-date-label').textContent = fmtDate(iso);
  renderClientDateCalendar();
}

/* Issues a fresh quotation for a different shipping date, priced from the
   latest forecast. Same shape as regenerateQuotation(), but driven by the
   client's date choice rather than by expiry. */
async function requoteForDate(iso) {
  const cf = state.currentForecast;
  if (!cf) return;

  try {
    const fresh = await insertHistoryRecord({
      company: cf.company, pic: cf.pic, route: cf.routeId,
      isdDate: cf.isdDate, containers: cf.containers,
      isdFee: cf.isdRow.f, lowDate: cf.lowestRow.date, lowFee: cf.lowestRow.f,
      clientDate: iso,
    });
    cf.clientDate = iso;
    cf.pendingId  = fresh.id;
  } catch (e) {
    console.error('Failed to start a new quotation:', e);
    alert('Could not start a new quotation. Please check your connection and try again.');
    return;
  }

  /* Same reasoning as regenerateQuotation(): the user confirmed a re-quote
     for a new date, so it is issued immediately rather than left as a draft. */
  await issueQuotationNow();
}

document.addEventListener('click', e => {
  const panel = document.getElementById('client-date-panel');
  if (panel && !panel.classList.contains('hidden') && !e.target.closest('#client-date-picker')) {
    panel.classList.add('hidden');
  }
});

function recordClientChoice() {
  const cf = state.currentForecast;
  if (!cf) return;
  /* Show the status picker modal */
  document.getElementById('record-modal').classList.remove('hidden');
}

async function confirmRecordChoice(status) {
  document.getElementById('record-modal').classList.add('hidden');
  const cf = state.currentForecast;
  if (!cf) return;

  /* Update the auto-saved Pending record in-place */
  await updateHistoryRecord(cf.pendingId, {
    clientDate: cf.clientDate,
    status,
    decision: status === 'Confirmed' ? cf.clientDate : null,
  });

  const isConfirmed = status === 'Confirmed';
  const statusEl = document.getElementById('decision-status-text');
  statusEl.textContent = status;
  statusEl.className   = isConfirmed ? 'status-confirmed' : 'status-pending';

  const btn = document.getElementById('record-btn');
  btn.disabled = true;
  btn.style.opacity = '0.65';
  btn.textContent = 'Choice Recorded';
  reInitLucide();
}

function closeRecordModal() {
  document.getElementById('record-modal').classList.add('hidden');
}

/* Prints the issued quotation. Every value comes from the frozen record,
   never from the live forecast, so a PDF exported on day two of the
   validity window is identical to one exported on day one. */
function exportQuotePDF() {
  const cf  = state.currentForecast;
  const rec = currentQuoteRecord();
  if (!cf) return;
  if (!isIssued(rec)) {
    alert('Generate the quotation first — the PDF carries its reference and validity period.');
    return;
  }

  const f = quoteFigures(cf, rec);

  const ov = document.getElementById('print-overlay');
  ov.innerHTML = `<div style="max-width:680px;margin:0 auto;padding:40px;font-family:'Inter',sans-serif;">
    <div style="display:flex;align-items:center;gap:14px;border-bottom:2px solid #2563eb;padding-bottom:18px;margin-bottom:22px;">
      <div style="font-size:26px;font-weight:800;"><span style="color:#0f172a;">Ship</span><span style="color:#2563eb;">Sense</span></div>
      <div style="color:#64748b;font-size:13px;">Client Quotation Document</div>
      <div style="margin-left:auto;text-align:right;">
        <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.04em;">Quotation Ref</div>
        <div style="font-size:15px;font-weight:700;color:#0f172a;">${rec.quoteRef}</div>
      </div>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr><td style="padding:9px 0;color:#64748b;width:200px;">Route</td><td style="font-weight:600;">${ROUTES[cf.routeId].label}</td></tr>
      <tr><td style="padding:9px 0;color:#64748b;">Company</td><td style="font-weight:600;">${cf.company}</td></tr>
      <tr><td style="padding:9px 0;color:#64748b;">Person in Charge</td><td style="font-weight:600;">${cf.pic}</td></tr>
      <tr><td style="padding:9px 0;color:#64748b;">Client Selected Date</td><td style="font-weight:600;">${fmtDate(f.clientDate)}</td></tr>
      <tr><td style="padding:9px 0;color:#64748b;">Containers</td><td style="font-weight:600;">${cf.containers} FEU (40ft)</td></tr>
      <tr><td style="padding:9px 0;color:#64748b;">Date &amp; Time Issued</td><td style="font-weight:600;">${fmtDateTime(rec.issuedAt)}</td></tr>
      <tr><td style="padding:9px 0;color:#64748b;">Valid Until</td><td style="font-weight:600;">${fmtDateTime(rec.validUntil)}</td></tr>
      <tr style="border-top:2px solid #2563eb;">
        <td style="padding:14px 0;font-weight:700;font-size:16px;">Quotation Price</td>
        <td style="font-weight:800;font-size:22px;color:#2563eb;">${fmt(rec.quotedPrice)}</td>
      </tr>
    </table>
    <div style="margin-top:24px;padding:12px 16px;background:#f8fafc;border-radius:8px;font-size:12px;color:#64748b;line-height:1.6;">
      ${validityStatement(f)}
    </div>
  </div>`;
  ov.classList.remove('hidden');
  window.print();
  ov.classList.add('hidden');
}

/* ===== FORECAST HISTORY ===== */
function renderHistory() {
  applyHistoryFilters();
  /* Returning to this page keeps whichever tab was last open, so refresh the
     revisions view too rather than leaving it on a stale render. */
  const revPanel = document.getElementById('hist-tab-panel-revisions');
  if (revPanel && !revPanel.classList.contains('hidden')) {
    seedRevisionFilters();
    renderRevisionHistory();
  }
}

/* ===== FORECAST REVISIONS TAB =====
   Tracks how the prediction for one fixed shipment date moved across every
   forecast run, which is the run-by-run view behind the two-run summary on
   the Forecast Result page. */
function switchHistoryTab(tab) {
  document.querySelectorAll('.exec-tab[data-hist-tab]').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.histTab === tab);
  });
  document.querySelectorAll('.hist-tab-panel').forEach(panel => {
    panel.classList.toggle('hidden', panel.id !== `hist-tab-panel-${tab}`);
  });
  if (tab === 'revisions') {
    seedRevisionFilters();
    renderRevisionHistory();
  }
}

/* Opens the Revisions tab on the date the user is already working with —
   the ISD of the forecast or quotation currently in hand — instead of on an
   empty picker with nothing rendered under it.

   A date the user typed themselves always wins, and keeps winning after
   they navigate away and back. That is why the last seeded value is
   remembered: it is the one thing that can be safely replaced when the
   selected forecast moves to a different ISD. */
function seedRevisionFilters() {
  const cf = state.currentForecast;
  if (!cf) return;

  const isdEl = document.getElementById('rev-isd');
  if (!isdEl) return;
  if (isdEl.value && isdEl.value !== state.revIsdSeeded) return;
  if (isdEl.value === cf.isdDate) return;

  isdEl.value = cf.isdDate;
  state.revIsdSeeded = cf.isdDate;
  const routeEl = document.getElementById('rev-route');
  if (routeEl) routeEl.value = cf.routeId;
}

/* Bumped on every call so a slow run-fetch from an earlier selection can't
   overwrite the output of a newer one. */
let revisionRenderToken = 0;

async function renderRevisionHistory() {
  const box = document.getElementById('rev-hist-body');
  if (!box) return;

  const token   = ++revisionRenderToken;
  const routeId = document.getElementById('rev-route')?.value || FIXED_ROUTE;
  const isoDate = document.getElementById('rev-isd')?.value;

  const note = msg => `<div class="table-card rev-empty">${msg}</div>`;

  if (!isoDate) {
    box.innerHTML = note('Select an intended shipment date to see how its prediction has changed across forecast runs.');
    return;
  }

  box.innerHTML = note('Loading forecast runs…');
  let runs;
  try {
    runs = await loadAllRuns();
  } catch (e) {
    console.error('Failed to load forecast runs:', e);
    if (token === revisionRenderToken) box.innerHTML = note('Could not load forecast runs from Supabase.');
    return;
  }
  if (token !== revisionRenderToken) return;

  /* Oldest first — a revision trail reads forward in time. A run only
     appears if its horizon actually covered this date. */
  const scale  = ROUTES[routeId]?.scale ?? 1;
  const series = runs.slice().reverse().reduce((acc, run) => {
    const row = run.forecast.find(d => d.date === isoDate);
    if (row) acc.push({ generatedAt: run.generatedAt, fee: row.f * scale });
    return acc;
  }, []);

  if (!series.length) {
    box.innerHTML = note(`No forecast run has covered ${fmtDate(isoDate)}. The model forecasts weekdays only, so weekends and dates beyond the 90-day horizon have no prediction.`);
    return;
  }

  const rows = series.map((pt, i) => {
    const prev   = i === 0 ? null : series[i - 1].fee;
    const change = prev === null ? null : pt.fee - prev;
    const dir    = change === null ? 'flat'
                 : Math.round(change) === 0 ? 'flat'
                 : change > 0 ? 'up' : 'down';
    const label  = change === null ? '<span class="rev-flat">—</span>'
                 : dir === 'flat' ? '<span class="rev-flat">No change</span>'
                 : `<span class="rev-${dir}">${change > 0 ? '+' : '−'}${fmt(Math.abs(change))}</span>`;
    return `<tr>
      <td><strong>${pklId(pt.generatedAt)}</strong><div class="rev-subtle">${fmtTs(pt.generatedAt)}</div></td>
      <td>${fmt(pt.fee)}</td>
      <td>${label}</td>
    </tr>`;
  }).join('');

  /* Two points make a comparison, not a trend — the chart only earns its
     space once there are three or more runs to plot. */
  const chart = series.length >= 3
    ? `<div class="table-card rev-chart-card">
         <h3 class="section-card-title">Prediction for ${fmtDate(isoDate)} over time</h3>
         <p class="section-card-sub">How each forecast run has valued this one shipment date &middot; USD / FEU</p>
         <div id="rev-chart"></div>
       </div>`
    : '';

  box.innerHTML = `${chart}
    <div class="table-card">
      <table class="hist-table rev-hist-table">
        <thead><tr>
          <th>Forecast generated</th>
          <th>Prediction for ${fmtDateShort(isoDate)}</th>
          <th>Change</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;

  if (series.length >= 3) renderRevisionChart(document.getElementById('rev-chart'), series);
}

/* Small self-contained line chart — the executive dashboard's chart helpers
   live inside that file's IIFE and aren't reachable from here, and this one
   plots a handful of points rather than a 90-day series. */
function renderRevisionChart(container, series) {
  if (!container) return;

  const W = 720, H = 260, m = { top: 18, right: 24, bottom: 42, left: 68 };
  const svgEl = (tag, attrs = {}, parent = null) => {
    const e = document.createElementNS('http://www.w3.org/2000/svg', tag);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(e);
    return e;
  };

  const fees = series.map(p => p.fee);
  const lo = Math.min(...fees), hi = Math.max(...fees);

  /* Axis ticks land on round hundreds rather than on the data's own min/max,
     so the gridlines read as 2,200 / 2,300 / 2,400 instead of arbitrary
     values. Step widens for bigger spreads to keep ~6 gridlines at most. */
  const step = [100, 200, 250, 500, 1000, 2000].find(s => (hi - lo) / s <= 6) ?? 5000;
  const yMin = Math.floor(lo / step) * step;
  const yMaxRaw = Math.ceil(hi / step) * step;
  const yMax = yMaxRaw === yMin ? yMin + step : yMaxRaw;

  const x = i => m.left + (series.length === 1 ? (W - m.left - m.right) / 2
                : (i / (series.length - 1)) * (W - m.left - m.right));
  const y = v => H - m.bottom - ((v - yMin) / (yMax - yMin)) * (H - m.top - m.bottom);

  container.innerHTML = '';
  container.style.position = 'relative';
  const svg = svgEl('svg', { viewBox: `0 0 ${W} ${H}`, class: 'rev-chart-svg' });
  container.appendChild(svg);

  for (let v = yMin; v <= yMax; v += step) {
    const yy = y(v);
    svgEl('line', { x1: m.left, x2: W - m.right, y1: yy, y2: yy, class: 'ss-gridline' }, svg);
    svgEl('text', { x: m.left - 10, y: yy + 4, 'text-anchor': 'end', class: 'rev-chart-axis' }, svg)
      .textContent = v.toLocaleString();
  }

  svgEl('path', {
    d: 'M ' + series.map((p, i) => `${x(i)},${y(p.fee)}`).join(' L '),
    fill: 'none', stroke: '#2563eb', 'stroke-width': 2.4,
  }, svg);

  series.forEach((p, i) => {
    svgEl('circle', { cx: x(i), cy: y(p.fee), r: 4.5, fill: '#fff', stroke: '#2563eb', 'stroke-width': 2.5 }, svg);
    /* End labels are anchored inward so the first and last run IDs don't get
       clipped by the SVG viewBox. */
    const anchor = i === 0 ? 'start' : i === series.length - 1 ? 'end' : 'middle';
    svgEl('text', { x: x(i), y: H - 22, 'text-anchor': anchor, class: 'rev-chart-axis' }, svg)
      .textContent = pklId(p.generatedAt);
    svgEl('text', { x: x(i), y: H - 8, 'text-anchor': anchor, class: 'rev-chart-axis rev-chart-axis-soft' }, svg)
      .textContent = fmtTs(p.generatedAt);
  });

  /* Hover readout — same crosshair-plus-tooltip behaviour as the executive
     dashboard's trend chart, so exact values stay off the axis. */
  const hoverLine = svgEl('line', {
    class: 'ss-hover-line', x1: 0, x2: 0, y1: m.top, y2: H - m.bottom, style: 'display:none;',
  }, svg);
  const dot = svgEl('circle', { r: 6, fill: '#2563eb', stroke: '#fff', 'stroke-width': 2.5, style: 'display:none;' }, svg);
  const overlay = svgEl('rect', {
    x: m.left, y: m.top, width: W - m.left - m.right, height: H - m.top - m.bottom,
    fill: 'transparent', style: 'cursor:crosshair;',
  }, svg);

  const tooltip = document.createElement('div');
  tooltip.className = 'ss-chart-tooltip';
  container.appendChild(tooltip);

  overlay.addEventListener('mousemove', evt => {
    const rect  = svg.getBoundingClientRect();
    const svgX  = ((evt.clientX - rect.left) / rect.width) * W;
    const ratio = (svgX - m.left) / (W - m.left - m.right);
    const idx   = Math.min(series.length - 1, Math.max(0, Math.round(ratio * (series.length - 1))));
    const pt    = series[idx];

    hoverLine.setAttribute('x1', x(idx));
    hoverLine.setAttribute('x2', x(idx));
    hoverLine.style.display = 'block';
    dot.setAttribute('cx', x(idx));
    dot.setAttribute('cy', y(pt.fee));
    dot.style.display = 'block';

    const cRect = container.getBoundingClientRect();
    tooltip.style.display = 'block';
    tooltip.style.left = Math.min(evt.clientX - cRect.left + 12, cRect.width - 160) + 'px';
    tooltip.style.top  = (evt.clientY - cRect.top - 12) + 'px';
    tooltip.innerHTML  = `<b>${pklId(pt.generatedAt)} · ${fmtTs(pt.generatedAt)}</b><span>${fmt2(pt.fee)} / FEU</span>`;
  });
  overlay.addEventListener('mouseleave', () => {
    hoverLine.style.display = 'none';
    dot.style.display = 'none';
    tooltip.style.display = 'none';
  });
}

function applyHistoryFilters() {
  const dateFrom = document.getElementById('filter-date-from').value;
  const company  = document.getElementById('filter-company').value.toLowerCase();
  const route    = document.getElementById('filter-route').value;
  const status   = document.getElementById('filter-status').value;

  let list = HISTORY_DATA.filter(h => {
    if (dateFrom && h.isdDate < dateFrom) return false;
    if (company && !h.company.toLowerCase().includes(company) && !h.pic.toLowerCase().includes(company)) return false;
    if (route  && !(ROUTES[h.route]?.label || h.route).toLowerCase().includes(route)) return false;
    if (status && h.status !== status) return false;
    return true;
  });

  const tbody = document.getElementById('history-tbody');
  tbody.innerHTML = list.map(h => {
    const r       = ROUTES[h.route];
    const isdFmt  = fmt(h.isdFee);
    const lowFmt  = fmt(h.lowFee);
    /* Confirmed rows show what the client actually agreed to: the frozen
       quotation price when one was issued, falling back to the computed
       lowest-date price for records that predate issued quotations. */
    const agreed  = h.quotedPrice != null ? h.quotedPrice : h.lowFee * h.containers * MARKUP;
    const decLine = h.decision
      ? `<div style="font-weight:600;color:#059669;font-size:13px;">${fmtDate(h.decision)}</div><div style="font-size:11px;color:#64748b;">${fmt(agreed)}</div>`
      : h.status === 'Cancelled'
        ? '<span style="color:#dc2626;font-size:12px;">Client cancelled</span>'
        : '<span style="color:#94a3b8;">–</span>';
    const pillCss = h.status === 'Confirmed' ? 'pill-confirmed'
                  : h.status === 'Cancelled'  ? 'pill-cancelled'
                  : 'pill-pending';
    /* What a row still permits depends on how far it has travelled, and the
       three stages are deliberately different:
         un-issued + Pending — nothing has been promised to anyone: editable,
                               cancellable, deletable.
         issued   + Pending  — a price is out with the client. Its terms are
                               frozen (schema.sql's lock trigger), but the
                               request can still be withdrawn or cancelled.
         decided             — Confirmed or Cancelled. This is the record of
                               something that happened; read-only, permanently.
       The buttons only mirror rules the database enforces on its own. */
    const editable  = h.status === 'Pending' && !h.issuedAt;
    const openReq   = h.status === 'Pending';
    const actions = `<div class="row-actions">
        <button class="btn-view" onclick="viewHistory('${h.id}')">View</button>
        ${editable ? `<button class="btn-edit" onclick="openEditModal('${h.id}')">Edit</button>` : ''}
        ${openReq  ? `<button class="btn-cancel" onclick="cancelHistory('${h.id}')">Cancel</button>` : ''}
        ${openReq  ? `<button class="btn-delete" onclick="deleteHistory('${h.id}')">Delete</button>` : ''}
      </div>`;
    return `<tr>
      <td><div class="td-date-main">${h.ts.split('\n')[0]}</div><div class="td-date-time">${h.ts.split('\n')[1]}</div>
        ${h.quoteRef ? `<div class="td-quote-ref">${h.quoteRef}</div>` : ''}</td>
      <td><div class="td-company">${h.company}</div><div class="td-pic">${h.pic}</div></td>
      <td style="font-size:12.5px;max-width:200px;">${r ? r.origin + ' →<br>' + r.dest : h.route}</td>
      <td style="font-size:12.5px;">ISD: ${fmtDate(h.isdDate)}<br>Qty: ${h.containers} FEU</td>
      <td><div class="td-fee-main">${isdFmt}/FEU</div><div class="td-fee-low">Lowest: ${lowFmt}/FEU</div></td>
      <td>${decLine}</td>
      <td><span class="status-pill ${pillCss}">${h.status}</span></td>
      <td>${actions}</td>
    </tr>`;
  }).join('') || '<tr><td colspan="8" style="text-align:center;color:#94a3b8;padding:28px;">No records found.</td></tr>';
}

function clearHistoryFilters() {
  ['filter-date-from','filter-company','filter-route','filter-status'].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.value = '';
  });
  applyHistoryFilters();
}

function viewHistory(id) {
  // id arrives as a string from the onclick attribute; HISTORY_DATA.id is
  // numeric (Supabase bigint) — compare as strings either way.
  const h = HISTORY_DATA.find(x => String(x.id) === String(id));
  if (!h) return;

  /* Reconstruct the forecast state from the history record */
  const data    = scaledData(h.route);
  let isdRow    = data.find(d => d.date === h.isdDate);
  if (!isdRow)  isdRow = data.reduce((best, d) =>
    Math.abs(new Date(d.date) - new Date(h.isdDate)) <
    Math.abs(new Date(best.date) - new Date(h.isdDate)) ? d : best, data[0]);

  let lowRow    = data.find(d => d.date === h.lowDate) || isdRow;

  const isdIdx  = data.indexOf(isdRow);
  const wStart  = Math.max(0, isdIdx - 5);
  const wEnd    = Math.min(data.length - 1, isdIdx + 5);

  /* An issued quotation reopens at its own numbers, not today's — the fees
     these two rows carry are what the page prices from. (Done after the
     window is sliced, which still needs the live row's index.) */
  if (h.issuedAt) {
    isdRow = { ...isdRow, date: h.isdDate, f: Number(h.isdFee) };
    lowRow = { ...lowRow, date: h.lowDate, f: Number(h.lowFee) };
  }

  state.currentForecast = {
    routeId:    h.route,
    isdDate:    h.isdDate,
    containers: h.containers,
    company:    h.company,
    pic:        h.pic,
    isdRow,
    lowestRow:  lowRow,
    dayWindow:  data.slice(wStart, wEnd + 1),
    allData:    data,
    clientDate: h.clientDate || lowRow.date,
    pendingId:  h.id,   /* prevents renderClientQuote from creating a duplicate entry */
  };

  navigateTo('client-quote');
}

async function cancelHistory(id) {
  const h = HISTORY_DATA.find(x => String(x.id) === String(id));
  if (!h || h.status !== 'Pending') return;
  if (!confirm(`Cancel this forecast for ${h.company}?\nThis cannot be undone.`)) return;
  await updateHistoryRecord(h.id, { status: 'Cancelled', decision: null });
  applyHistoryFilters();
  /* If the currently open quote belongs to this record, reflect cancelled state */
  if (state.currentForecast && String(state.currentForecast.pendingId) === String(id)) {
    document.getElementById('decision-status-text').textContent = 'Cancelled';
    document.getElementById('decision-status-text').className   = 'status-cancelled';
    const btn = document.getElementById('record-btn');
    btn.disabled = true;
    btn.style.opacity = '0.45';
    btn.textContent = 'Quote Cancelled';
  }
}

/* ===== UPDATE =====
   Edits a saved request in place. Only reachable while the record is still
   Pending and un-issued: once a price has gone to the client, the database
   rejects changes to these very fields (schema.sql's lock trigger), so
   offering the form at all would be offering something that cannot work. */
function openEditModal(id) {
  const h = HISTORY_DATA.find(x => String(x.id) === String(id));
  if (!h || h.status !== 'Pending' || h.issuedAt) return;

  state.editingId = h.id;
  document.getElementById('edit-company').value    = h.company;
  document.getElementById('edit-pic').value        = h.pic;
  document.getElementById('edit-containers').value = h.containers;

  const isdEl = document.getElementById('edit-isd');
  isdEl.value = h.isdDate;
  if (FORECAST_DATA.length) {
    isdEl.min = FORECAST_DATA[0].date;
    isdEl.max = FORECAST_DATA[FORECAST_DATA.length - 1].date;
  }

  document.getElementById('edit-error').classList.add('hidden');
  document.getElementById('edit-modal').classList.remove('hidden');
}

function closeEditModal() {
  document.getElementById('edit-modal').classList.add('hidden');
  state.editingId = null;
}

async function saveEditRecord(e) {
  if (e) e.preventDefault();
  const id = state.editingId;
  const h  = HISTORY_DATA.find(x => String(x.id) === String(id));
  if (!h) return;

  const err  = document.getElementById('edit-error');
  const show = msg => { err.textContent = msg; err.classList.remove('hidden'); };

  const company    = document.getElementById('edit-company').value.trim();
  const pic        = document.getElementById('edit-pic').value.trim();
  const containers = parseInt(document.getElementById('edit-containers').value, 10);
  const isdDate    = document.getElementById('edit-isd').value;

  /* Validated here as well as by the input attributes, because the attributes
     only guard typing — they say nothing about what this function receives. */
  if (!company) return show('Company name is required.');
  if (!pic)     return show('Person in Charge (PIC) is required.');
  if (!Number.isInteger(containers) || containers < 1 || containers > 500) {
    return show('Number of containers must be a whole number between 1 and 500.');
  }
  if (!isdDate) return show('Intended Ship Date is required.');

  const minDate = FORECAST_DATA[0]?.date;
  const maxDate = FORECAST_DATA[FORECAST_DATA.length - 1]?.date;
  if (minDate && (isdDate < minDate || isdDate > maxDate)) {
    return show(`Intended Ship Date must be between ${fmtDate(minDate)} and ${fmtDate(maxDate)}.`);
  }

  const patch = { company, pic, containers, isdDate };

  /* A moved ship date invalidates the fee columns stored beside it, so they
     are recomputed from the current forecast rather than left describing a
     date the record no longer refers to. */
  if (isdDate !== h.isdDate) {
    const data   = scaledData(h.route);
    const isdRow = data.find(d => d.date === isdDate) ||
      data.reduce((best, d) =>
        Math.abs(new Date(d.date) - new Date(isdDate)) <
        Math.abs(new Date(best.date) - new Date(isdDate)) ? d : best, data[0]);
    const i   = data.indexOf(isdRow);
    const win = data.slice(Math.max(0, i - 5), Math.min(data.length - 1, i + 5) + 1);
    const low = win.reduce((mn, d) => d.f < mn.f ? d : mn, win[0]);

    patch.isdFee     = isdRow.f;
    patch.lowDate    = low.date;
    patch.lowFee     = low.f;
    patch.clientDate = isdRow.date;
  }

  const btn = document.getElementById('edit-save-btn');
  btn.disabled = true;
  try {
    await updateHistoryRecord(id, patch);
  } catch (ex) {
    console.error('Failed to update record:', ex);
    btn.disabled = false;
    return show('Could not save changes. Please check your connection and try again.');
  }
  btn.disabled = false;

  closeEditModal();
  applyHistoryFilters();
}

/* ===== DELETE =====
   The only operation here that destroys data, so it asks first and names
   what is about to go. The database has the final say (schema.sql's delete
   policy and guard) — a refusal there is reported rather than swallowed. */
async function deleteHistory(id) {
  const h = HISTORY_DATA.find(x => String(x.id) === String(id));
  if (!h) return;

  const warning = h.quoteRef
    ? `Delete quotation ${h.quoteRef} for ${h.company}?\n\n` +
      `A price was already issued to this client. Deleting removes that record entirely.\n\nThis cannot be undone.`
    : `Delete the saved forecast record for ${h.company}?\n\nThis cannot be undone.`;
  if (!confirm(warning)) return;

  try {
    await deleteHistoryRecord(h.id);
  } catch (e) {
    console.error('Failed to delete record:', e);
    alert(e.blocked
      ? 'This record can no longer be deleted — a client decision has been recorded against it.'
      : 'Could not delete this record. Please check your connection and try again.');
    return;
  }

  /* The Client Quote page may still be holding the row that just vanished.
     Clearing the id lets that page fall back to its unsaved state instead of
     rendering against a record the database no longer has. */
  if (state.currentForecast && String(state.currentForecast.pendingId) === String(id)) {
    state.currentForecast.pendingId = null;
  }
  applyHistoryFilters();
}

['filter-status'].forEach(id => {
  const el = document.getElementById(id);
  if (el) el.addEventListener('change', applyHistoryFilters);
});
['filter-company','filter-route','filter-date-from'].forEach(id => {
  const el = document.getElementById(id);
  if (el) el.addEventListener('input', applyHistoryFilters);
});

/* ===== INIT ===== */
document.addEventListener('DOMContentLoaded', async () => {
  const submitBtn = document.querySelector('#login-form button[type="submit"]');
  const loginErr  = document.getElementById('login-error');
  submitBtn.disabled = true;
  submitBtn.textContent = 'Loading forecast data…';

  try {
    /* Two newest distinct runs: [0] is the latest, [1] the immediately
       previous one used for the revision comparison on the Forecast Result
       page. Each ingest appends a snapshot row, so id order is run order. */
    const index = await fetchSnapshotIndex();
    if (!index.length) throw new Error('no forecast data ingested yet');
    const runs = await fetchSnapshotRuns(index.slice(0, 2).map(r => r.id));
    if (!runs[0]?.forecast?.length) throw new Error('no forecast data ingested yet');

    FORECAST_DATA = runs[0].forecast;
    FORECAST_META = { generatedAt: runs[0].generatedAt };

    if (runs[1]) {
      PREV_FORECAST_DATA = runs[1].forecast;
      PREV_FORECAST_META = { generatedAt: runs[1].generatedAt };
    }
    submitBtn.disabled = false;
    submitBtn.textContent = 'Login';
  } catch (e) {
    console.error('Failed to load forecast data:', e);
    submitBtn.textContent = 'Data unavailable';
    loginErr.textContent  = 'Could not load forecast data from Supabase. Check SUPABASE_URL/SUPABASE_ANON_KEY and that a forecast snapshot has been ingested.';
    loginErr.classList.remove('hidden');
  }

  try {
    await initHistory();
  } catch (e) {
    console.error('Failed to load quote history:', e);
    HISTORY_DATA = [];
  }

  const today = new Date().toISOString().slice(0,10);
  const isdEl = document.getElementById('input-isd');
  if (isdEl) isdEl.value = today;
  applyIsdBounds();
  reInitLucide();

  /* Executive Dashboard's floating "Back to Top" button — shows once the
     page scrolls past 300px (the app scrolls at the window level, not
     inside .page-area). The button itself lives inside #page-executive,
     so it's already hidden on every other page/tab regardless of this
     listener still running while they're active. */
  const backToTopBtn = document.getElementById('exec-back-to-top');
  if (backToTopBtn) {
    window.addEventListener('scroll', () => {
      backToTopBtn.classList.toggle('visible', window.scrollY > 300);
    });
  }
});
